addons:
  apt_packages:
    - lib32stdc++6
env:
  - SMVERSION=1.10
script:
  - git submodule update --init
  - git clone https://github.com/splewis/sm-builder
  - cd sm-builder
  - pip install --user -r requirements.txt
  - python setup.py install --prefix=~/.local
  - cd ..
  - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMVERSION}"
  - wget $SMPACKAGE
  - tar xfz $(basename $SMPACKAGE)
  - cd addons/sourcemod/scripting/
  - chmod +x spcomp
  - PATH+=":$PWD"
  - cd include
  - wget https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
  - cd ../../../..
  - cp -r ./dependencies/sm-json/addons/sourcemod/scripting/include/* ./addons/sourcemod/scripting/include
  - cp -r ./dependencies/System2/sourcemod/scripting/include/* ./addons/sourcemod/scripting/include
deploy:
  - provider: script
    script: bash build.sh
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key: $GITHUB_OAUTH_TOKEN
    file: get5.zip
    on:
      tags: true
    cleanup: false
  - provider: script
    script: bash build.sh beta
    on:
      all_branches: true
      tags: false
  - provider: releases
    name: Beta $TRAVIS_COMMIT $TRAVIS_BRANCH
    api_key: $GITHUB_OAUTH_TOKEN
    file: get5.zip
    on:
      all_branches: true
      tags: false
    cleanup: false

notifications:
  email: true